name: manager
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.1
  yaml_modify: ^1.0.1
  yaml_writer: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
